#!/usr/bin/env bash

if [ $# -ne 2 ]; then
  >&2 echo "Usage: $0 <author> <commit>"
  exit 1
fi

AUTHOR=$1
AUTHOR_NAME=$(echo $AUTHOR | perl -wlne '/^(.*)\s*<.*>$/ and print $1')
AUTHOR_EMAIL=$(echo $AUTHOR | perl -wlne '/^.*\s*<(.*)>$/ and print $1')
COMMIT=$(git rev-parse --short $2)

CURRENT_AUTHOR=$(git --no-pager show -s --format="%aN" $COMMIT)
CURRENT_COMMIT_MESSAGE=$(git log -n 1 --pretty=format:%s $COMMIT)
NEW_COMMIT_MESSAGE=$(echo " $CURRENT_COMMIT_MESSAGE " | grep '[^a-zA-Z\d]$CURRENT_AUTHOR[^a-zA-Z\d]'| sed -e 's/$CURRENT_AUTHOR/$AUTHOR/g' -e 's/^ //;s/ $//')

{
  GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT/edit $COMMIT/'" git rebase -i $COMMIT~1^^ 
  GIT_COMMITTER_NAME="$AUTHOR_NAME" GIT_COMMITTER_EMAIL="$AUTHOR_EMAIL" git commit --amend -m "$NEW_COMMIT_MESSAGE" --author="$AUTHOR"  
  git rebase --continue
} &> /dev/null

echo "$AUTHOR_NAME is now the author of $COMMIT. You're officially an asshole.";
